### ISSUE TITLE
LilyGO HiGrow sensor enhancements

### ISSUE THREAD

**Issue by BeardedTinker** [BeardedTinker/Home-Assistant_Config#3]
New firmware from [Pesor ](https://github.com/pesor/LilyGO-TTGO-HiGrow) will support much easier configuration and abbility to add sensor faster to Home Assistant. This is Alpha version of custom component - still some work left to do.

**Comment by BeardedTinker** [comment]
New version is in the works by @pesor - closing this for now.

**Comment by BeardedTinker** [comment]
Splitting plant integration into separate files for each plant. Few more boards ordered and this is needed to keep everything nice and tidy.
Also fixed are minimum/maximum values for plants I have.

**Comment by BeardedTinker** [comment]
I wanted to track how long do batteries last. That is also very specific to each board.
In order to do that I've done following:
- created input_datetime.X for each plant sensor board. 
- automation that is triggerd when plant sensor get in "charging" status. It then inputs current timestamp into input_datetime
- template sensor that converts static date to counter, counting days from
There probably is easier and less complicated way to do so, but this one retains data over HA restarts. 
Using history_stats and last_update or last_change didn't work.

**Comment by pesor** [comment]
Hi Andrej,

This is actually a great idea.

I saw your solution on my Github.

I can program it into the C++ code, so that you do not have to make yaml entries, it will then work automatically with the sensor last-charge-date, this will also be added to the MQTT message.

Do you like my proposal.


Right now I am fighting two issues.

First is the Fronius-Data-Manager, which gives me problems on month change, and problems when the inverter is not producing any power. This means that data in the MQTT is not consistent.

I need to check for sunset, and production, in order to get this right. So this is what I am programming right now.

Second issue is SDCard and ESP32, I thought it was simple, but that is not the case, as I simply cannot get it to work because of some incompatibilities. I found an YouTube video, that might solve my problem, so after my Fronius, and then the TTGO-T-HIGrow changes, if you like them, I will start with the SDCard ESP32 implementation.

Best regards,
Per

Fra: BeardedTinker <notifications@github.com>
Sendt: 5. december 2020 11:50
Til: BeardedTinker/Home-Assistant_Config <Home-Assistant_Config@noreply.github.com>
Cc: Per Rose <post@per-rose.dk>; Mention <mention@noreply.github.com>
Emne: Re: [BeardedTinker/Home-Assistant_Config] LilyGO HiGrow sensor enhancements (#3)


I wanted to track how long do batteries last. That is also very specific to each board.
In order to do that I've done following:

  *   created input_datetime.X for each plant sensor board.
  *   automation that is triggerd when plant sensor get in "charging" status. It then inputs current timestamp into input_datetime
  *   template sensor that converts static date to counter, counting days from
There probably is easier and less complicated way to do so, but this one retains data over HA restarts.
Using history_stats and last_update or last_change didn't work.

**Comment by BeardedTinker** [comment]
Adding 2 more boards with 4.1.0 firmware. Also testing new DS18B20 external soil temperature sensor.
