### ISSUE TITLE
Chromecast Radio streaming: volume sync issue / Volume 0/100 instead of 0/1

### ISSUE THREAD

**Issue by johanvh83** [BeardedTinker/Home-Assistant_Config#41]
Hi BeardedTinker,

Many thanks for your well explained Youtube video to setup chromecast radio streaming.

All works fine except the volume sync issue.

When I use the card I made and press 'Execute' the selected media.player starts playing the source with the selected volume.
When I change the volume in the card, nothing happens on the media.player. If I press again 'execute' the media player stops playing (I guess it loads again the radio stream) and after few seconds it starts to play again with the corrected volume.

Is there a way to avoid this silence? Meaning change the script only to change the volume and not to load again the audio stream?

Furthermore I like more a volume setting from 0 to 100 instead of 0 to 1. I changed the input_number.yaml but got an error. Searched the internet and found the script must be changed from:
volume_level: '{{  states("input_number.radio_volume")  }}'
to
volume_level: '{{  states("input_number.radio_volume")|int/100  }}'

After this change the error disappeared but when I execute your script, the mediaplayer always starts with volume 0 and I cannot longer control the volume from the media player by your script.

Thanks for your help!
Johan (Belgium)

**Comment by BeardedTinker** [comment]
Hi Johan and thanks for the this post.

You can look at my extended radio that I've only made available here - on GItHub...
https://github.com/BeardedTinker/Home-Assistant_Config/issues/29 and commit #f80c4c6 - there I have Volume Up/Volume Down as switches. It allows to increase/decrease volume.

As for the volume (media player) - it supports values from 0 to 1... https://www.home-assistant.io/integrations/media_player/#service-media_playervolume_set

The problem is this rounding with int/100 I think, not 100% sure, but I think it rounds number to 1 or 0.
